apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ibp1blw4k-nodejs
  janus-idp.io/tekton: ibp1blw4k-nodejs
  backstage.io/kubernetes-id: ibp1blw4k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ibp1blw4k-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
